dn42:
  vars:
    ownas: 4242422558
    ownasnet: 172.23.120.16/28
    ownasnet6: fd93:6001:6ed9::/48
    ownasnetset: "[172.23.120.16/28+]"
    ownasnetset6: "[fd93:6001:6ed9::/48+]"

  hosts:
    au-bne1:
      ansible_host: au-bne1.dn42.derix.au
      node_id: 30000
      ownip: 172.23.120.17
      ownip6: fd93:6001:6ed9:0::1
      link_local6: fe80::2558:0
      dn42_region: 53 # Pacific & Oceania
      dn42_country: 1036 # Australia
      location: Brisbane, Australia
      latlng: [-27.4698, 153.0251]
      public_ipv4: nat
      public_ipv6: open
      wg_public: eg/oWzrAlYWT+MxLE0ikGT8qE7Otf3KMp4V7kGzC920=
      igp_links:
        - au-syd1

    au-syd1:
      ansible_host: au-syd1.dn42.derix.au
      node_id: 30001
      ownip: 172.23.120.18
      ownip6: fd93:6001:6ed9:1::1
      link_local6: fe80::2558:1
      dn42_region: 53 # Pacific & Oceania
      dn42_country: 1036 # Australia
      location: Sydney, Australia
      latlng: [-33.8688, 151.2093]
      public_ipv4: open
      public_ipv6: open
      wg_public: Lhg2KWIFATOatdf/qLyTmAs0XEImX2oPzqoZKCMMlw8=
      igp_links:
        - us-pdx1
        - au-syd2
        - jp-tyo1
        - au-bne1
        - us-nyc1
        - sg-sin1
        - us-lax1

    us-pdx1:
      node_id: 30002
      ansible_host: us-pdx1.dn42.derix.au
      ownip: 172.23.120.19
      ownip6: fd93:6001:6ed9:2::1
      link_local6: fe80::2558:2
      dn42_region: 44 # North America West
      dn42_country: 1840 # United States
      location: Portland, US West
      latlng: [45.5231, -122.6765]
      public_ipv4: open
      public_ipv6: closed
      wg_public: pEgl/q/fxrcdnqEur25ZKrIkOvoISDVBrU80R86jY1Q=
      igp_links:
        - au-syd1
        - us-nyc1
        - nl-ams1

    us-nyc1:
      node_id: 30003
      ansible_host: us-nyc1.dn42.derix.au
      ownip: 172.23.120.20
      ownip6: fd93:6001:6ed9:3::1
      link_local6: fe80::2558:3
      dn42_region: 42 # North America East
      dn42_country: 1840 # United States
      location: New York City, US East
      latlng: [40.7128, -74.0060]
      public_ipv4: open
      public_ipv6: open
      wg_public: UILRrlUwHZE4NWdV7RvF5Jit5G1eLwZ2V5p3sFYbk3M=
      igp_links:
        - us-pdx1
        - nl-ams1
        - uk-bhx1
        - au-syd1
        - us-coe1
        - us-chi1
        - us-jax1
        - ca-mtl1
        - us-lax1

    nl-ams1:
      node_id: 30004
      ansible_host: nl-ams1.dn42.derix.au
      ownip: 172.23.120.21
      ownip6: fd93:6001:6ed9:4::1
      link_local6: fe80::2558:4
      dn42_region: 41 # Europe
      dn42_country: 1528 # Netherlands
      location: Amsterdam, Netherlands
      latlng: [52.3702, 4.8952]
      public_ipv4: open
      public_ipv6: open
      wg_public: aEnSuSUB3ZCrryPAIJxBtH6ZcNgCSeW+dMEceEbiflo=
      igp_links:
        - us-nyc1
        - us-pdx1
        - uk-bhx1
        - pl-waw1
        - jp-tyo1
        - us-chi1
        - fr-gra1
        - de-fsn1

    uk-bhx1:
      node_id: 30005
      ansible_host: uk-bhx1.dn42.derix.au
      ownip: 172.23.120.22
      ownip6: fd93:6001:6ed9:5::1
      link_local6: fe80::2558:5
      dn42_region: 41 # Europe
      dn42_country: 1826 # United Kingdom
      location: Birmingham, United Kingdom
      latlng: [52.4862, -1.8904]
      public_ipv4: nat
      public_ipv6: open
      wg_public: pmJ4rrY1jei9Z4gvbuiiIp8RRqVh/fBStpYt6X11NRM=
      igp_links:
        - us-nyc1
        - nl-ams1
        - pl-waw1
        - us-jax1
        - fr-gra1

    pl-waw1:
      node_id: 30006
      ansible_host: pl-waw1.dn42.derix.au
      ownip: 172.23.120.23
      ownip6: fd93:6001:6ed9:6::1
      link_local6: fe80::2558:6
      dn42_region: 41 # Europe
      dn42_country: 1616 # Poland
      location: Warsaw, Poland
      latlng: [52.2297, 21.0122]
      public_ipv4: closed
      public_ipv6: open
      wg_public: nP2cdLT+WzT2EgHLeOsVPeDivJjXPRurP5RpMnTFmR4=
      igp_links:
        - nl-ams1
        - uk-bhx1
        - de-fsn1

    us-lax1:
      node_id: 30007
      ansible_host: us-lax1.dn42.derix.au
      ownip: 172.23.120.24
      ownip6: fd93:6001:6ed9:7::1
      link_local6: fe80::2558:7
      dn42_region: 44 # North America West
      dn42_country: 1840 # United States
      location: Los Angeles, US West
      latlng: [34.0522, -118.2437]
      public_ipv4: closed
      public_ipv6: open
      wg_public: s3IVH2xJ3oRekd4x4Bc2H2pb0YZD11FT7Unxttc7GCU=
      igp_links:
        - au-syd1
        - us-nyc1
        - us-coe1


    au-syd2:
      ansible_host: au-syd2.dn42.derix.au
      node_id: 36001
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6001::1
      link_local6: fe80::2558:6001
      dn42_region: 53 # Pacific & Oceania
      dn42_country: 1036 # Australia
      location: Sydney, Australia
      latlng: [-33.8688, 151.2093]
      public_ipv4: nat
      public_ipv6: open
      wg_public: g9OmILKtTKBPtWZYqOTNQRgy6RodvmL4PDnLh445ykk=
      igp_links:
        - au-syd1
        - us-coe1

    jp-tyo1:
      ansible_host: jp-tyo1.dn42.derix.au
      node_id: 36002
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6002::1
      link_local6: fe80::2558:6002
      dn42_region: 52 # Asia East
      dn42_country: 1392 # Japan
      location: Tokyo, Japan
      latlng: [35.6895, 139.6917]
      public_ipv4: nat
      public_ipv6: open
      wg_public: bx1/IAZAsKOghvXHpVGrSJVqpH4oeLvwYvS+Lyrgyx0=
      igp_links:
        - au-syd1
        - sg-sin1
        - us-coe1
        - us-chi1
        - nl-ams1

    sg-sin1:
      ansible_host: sg-sin1.dn42.derix.au
      node_id: 36003
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6003::1
      link_local6: fe80::2558:6003
      dn42_region: 51 # Asia South-East
      dn42_country: 1702 # Singapore
      location: Singapore
      latlng: [1.3521, 103.8198]
      public_ipv4: nat
      public_ipv6: open
      wg_public: v7QTxS85pDHQ2cmNCaRiiztVeA5w9g+LnuYGglLyqT8=
      igp_links:
        - au-syd1
        - jp-tyo1
        - fr-gra1
        - us-coe1

    us-coe1:
      ansible_host: us-coe1.dn42.derix.au
      node_id: 36004
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6004::1
      link_local6: fe80::2558:6004
      dn42_region: 44 # North America West
      dn42_country: 1840 # United States
      location: Coeur d'Alene, US West
      latlng: [47.6777, -116.7805]
      public_ipv4: nat
      public_ipv6: open
      wg_public: UxAaPvxdLsuR7xTrNd6biPuSb0NMexN7t4Hjh/9bMCI=
      igp_links:
        - au-syd2
        - jp-tyo1
        - sg-sin1
        - us-chi1
        - us-nyc1
        - us-lax1

    us-chi1:
      ansible_host: us-chi1.dn42.derix.au
      node_id: 36005
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6005::1
      link_local6: fe80::2558:6005
      dn42_region: 43 # North America Central
      dn42_country: 1840 # United States
      location: Chicago, US Central
      latlng: [41.8781, -87.6298]
      public_ipv4: nat
      public_ipv6: open
      wg_public: efmf1G0YPoNoPzyRPX0pl5wYxDMpKYrXSC7fSgL8uxI=
      igp_links:
        - jp-tyo1
        - us-coe1
        - us-jax1
        - us-nyc1
        - nl-ams1

    us-jax1:
      ansible_host: us-jax1.dn42.derix.au
      node_id: 36006
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6006::1
      link_local6: fe80::2558:6006
      dn42_region: 42 # North America East
      dn42_country: 1840 # United States
      location: Jacksonville, US East
      latlng: [30.3322, -81.6557]
      public_ipv4: nat
      public_ipv6: open
      wg_public: ZepzPTIEwT+kBceqwQhFt9fxyZc6pEOpn8QK6++LEDw=
      igp_links:
        - us-chi1
        - us-nyc1
        - uk-bhx1

    ca-mtl1:
      ansible_host: ca-mtl1.dn42.derix.au
      node_id: 36007
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6007::1
      link_local6: fe80::2558:6007
      dn42_region: 42 # North America West
      dn42_country: 1124 # Canada
      location: Montreal, Canada
      latlng: [45.5017, -73.5673]
      public_ipv4: nat
      public_ipv6: open
      wg_public: dMdZQvF2yosvWDHuQgfrshTs/AH50ylZbPBNHQll8xQ=
      igp_links:
        - us-nyc1
        - fr-gra1

    fr-gra1:
      ansible_host: fr-gra1.dn42.derix.au
      node_id: 36008
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6008::1
      link_local6: fe80::2558:6008
      dn42_region: 41 # Europe
      dn42_country: 1250 # France
      location: Gravelines, France
      latlng: [50.9871, 2.1278]
      public_ipv4: nat
      public_ipv6: open
      wg_public: qvIjUZ8L1YIu4VFdesQG5L6JttdrE+QQPVzdTRCa0lI=
      igp_links:
        - sg-sin1
        - ca-mtl1
        - nl-ams1
        - uk-bhx1
        - de-fsn1

    de-fsn1:
      ansible_host: de-fsn1.dn42.derix.au
      node_id: 36009
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6009::1
      link_local6: fe80::2558:6009
      dn42_region: 41 # Europe
      dn42_country: 1276 # Germany
      location: Falkenstein, Germany
      latlng: [50.4757, 12.3656]
      public_ipv4: nat
      public_ipv6: open
      wg_public: dUUYY/hJIeHpk8KvtwmHTRxf1ZLHgzLxLHBr8AXQyzk=
      igp_links:
        - fr-gra1
        - nl-ams1
        - pl-waw1
        - fi-hel1
        - bg-sof1

    fi-hel1:
      ansible_host: fi-hel1.dn42.derix.au
      node_id: 36010
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6010::1
      link_local6: fe80::2558:6010
      dn42_region: 41 # Europe
      dn42_country: 1246 # Finland
      location: Helsinki, Finland
      latlng: [60.1699, 24.9384]
      public_ipv4: nat
      public_ipv6: open
      wg_public: SW8xu8VstXTqwvWuhZw7I9sGgAH15DyMbGhvPpwvR0o=
      igp_links:
        - de-fsn1

    bg-sof1:
      ansible_host: bg-sof1.dn42.derix.au
      node_id: 36011
      dn42_v6_only: true
      ownip6: fd93:6001:6ed9:6011::1
      link_local6: fe80::2558:6011
      dn42_region: 41 # Europe
      dn42_country: 1100 # Bulgaria
      location: Sofia, Bulgaria
      latlng: [42.6977, 23.3219]
      public_ipv4: nat
      public_ipv6: open
      wg_public: i+oJ/HCJ7NGOIqRk41vjPzHXB+arwZTXpiU1kJjnTDs=
      igp_links:
        - de-fsn1


dn42_full: # KVM nodes
  hosts:
    au-bne1:
    au-syd1:
    us-pdx1:
    us-nyc1:
    nl-ams1:
    uk-bhx1:
    pl-waw1:
    us-lax1:

dn42_lite: # Small OpenVZ/LXC nodes
  hosts:
    au-syd2:
    jp-tyo1:
    sg-sin1:
    us-coe1:
    us-chi1:
    us-jax1:
    ca-mtl1:
    fr-gra1:
    de-fsn1:
    fi-hel1:
    bg-sof1:

dn42_dns_server: # DNS server
  hosts:
    au-bne1:
    au-syd1:

dn42_webserver: # Webserver
  hosts:
    au-bne1:

dn42_nat_gw: # NAT gateway for local network
  hosts:
    au-bne1:
      nat_iface: ens18
      nat_subnet: 10.102.0.0/16
