dn42:
  vars:
    ownas: 4242422558
    ownasnet: 172.23.120.16/28
    ownasnet6: fd93:6001:6ed9::/48
    ownasnetset: "[172.23.120.16/28+]"
    ownasnetset6: "[fd93:6001:6ed9::/48+]"

  hosts:
  #   au-bne1:
  #     ansible_host: au-bne1.dn42.derix.au
  #     node_id: 30000
  #     ownip: 172.23.120.17
  #     ownip6: fd93:6001:6ed9::1
  #     link_local: 169.254.8.0
  #     link_local6: fe80::6001:6ed9:0
  #     dn42_region: 53 # Pacific & Oceania
  #     dn42_country: 1036 # Australia
  #     igp_links:
  #       - au-syd1

    au-syd1:
      ansible_host: au-syd1.dn42.derix.au
      node_id: 30001
      ownip: 172.23.120.20
      ownip6: fd93:6001:6ed9:1::1
      link_local: 169.254.8.1
      link_local6: fe80::6001:6ed9:1
      dn42_region: 53 # Pacific & Oceania
      dn42_country: 1036 # Australia
      igp_links:
        - us-pdx1
        # - au-bne1

    us-pdx1:
      node_id: 30002
      ansible_host: us-pdx1.dn42.derix.au
      ownip: 172.23.120.21
      ownip6: fd93:6001:6ed9:2::1
      link_local: 169.254.8.2
      link_local6: fe80::6001:6ed9:2
      dn42_region: 44 # North America West
      dn42_country: 1840 # United States
      igp_links:
        - au-syd1
