- name: Install packages & software for all nodes
  hosts: dn42
  become: true

  roles:
    - 'install_wireguard'
    - 'install_bird'
    - 'install_bird_lgproxy_go'
    - 'install_dn42_roa'
    - 'install_pingfinder'
    - 'install_iptables'

- name: Install packages & software for DNS server nodes
  hosts: dn42_dns_server
  become: true

  roles:
    - 'install_dns_server'

- name: Install webserver
  hosts: dn42_webserver
  become: true

  roles:
    - 'install_webserver'
    - 'install_bird_lg_go'
