- name: Reconfigure packages & software for all nodes
  hosts: dn42
  become: true

  roles:
    - 'configure_dn42_node'
    - 'configure_iptables'
    - 'configure_bird'
    - 'configure_dn42_peers'

- name: Reconfigure packages & software for DNS server nodes
  hosts: dn42_dns_server
  become: true

  roles:
    - 'configure_dns_server'

- name: Reconfigure webserver
  hosts: dn42_webserver
  become: true

  roles:
    - 'configure_webserver'
    - 'configure_bird_lg_go'

- name: Reconfigure packages & software for nat64 nodes
  hosts: dn42_nat64
  become: true

  roles:
    - 'configure_jool'
