configure_dn42_peers_peerlist:
  - name: SUNNET
    as: "4242423088"
    remote_endpoint: sjc1-us.dn42.6700.cc:22558
    remote_pubkey: G/ggwlVSy5jKWFlJM01hxcWnL8VDXsD5EXZ/S47SmhM=
    remote_link_local: fe80::3088:191
    override_link_local: fe80::abcd
    extended_next_hop: "on"
    community_latency: 4
    community_bandwidth: 24

  - name: KSKB
    as: "4242421817"
    remote_endpoint: ussea.kskb.eu.org:22558
    remote_pubkey: WcbXsXIVIIXjEDKFrCnPH8lG9NaFDKdkvCA7Gl6j4UA=
    remote_link_local: fe80::1817
    extended_next_hop: "on"
    community_latency: 2
    community_bandwidth: 24

  - name: HIGHDEF
    as: "4242421080"
    remote_endpoint: yvr.peer.highdef.network:22558
    remote_pubkey: O4qWRgbJVdOM8ktyUQyT1s11WkR16JTgtnn42m9A2R8=
    remote_link_local: fe80::1080:35
    extended_next_hop: "on"
    community_latency: 3
    community_bandwidth: 23

  - name: NINEPFS
    as: "4242421146"
    remote_endpoint: 47.221.227.180:22558
    remote_pubkey: /SMD8YbgCtJ0iinMzRmeTfwv9GX4XxK/lCQCAnusu04=
    remote_link_local: fe80::1146:1
    extended_next_hop: "on"
    community_latency: 5
    community_bandwidth: 23
