- name: Update apt cache
  apt:
    update_cache: true

- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Install netfilter-persistent
  apt:
    name: netfilter-persistent
    state: present

- name: Create iptables directory
  file:
    path: "/etc/iptables"
    state: directory
    mode: "0755"
    owner: root
    group: root
