- name: Add repository ppa:cz.nic-labs/bird
  apt_repository:
    repo: ppa:cz.nic-labs/bird
    state: present

- name: Update apt
  apt:
    update_cache: true

- name: Install Bird
  apt:
    name: bird2
    state: present

- name: Create Bird peers folder
  file:
    path: /etc/bird/peers
    state: directory
    mode: "0755"
    owner: bird
    group: bird

- name: Create Bird ibgp folder
  file:
    path: /etc/bird/ibgp
    state: directory
    mode: "0755"
    owner: bird
    group: bird

# Prevents error on first run for nodes without any IPv4 addresses
- name: Add node ID to Bird config
  lineinfile:
    path: /etc/bird/bird.conf
    regexp: "^router id"
    line: "router id {{ node_id }};"

- name: Ensure Bird service is enabled and started
  service:
    name: bird
    state: started
    enabled: true
