- name: Update apt cache
  apt:
    update_cache: true

- name: Install bind9
  apt:
    name: bind9
    state: present

- name: Create zones directory
  file:
    path: /etc/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: "0755"
