- name: Restart pingfinder
  systemd:
    name: pingfinder.service
    daemon_reload: true
    state: started
    enabled: true

- name: Enable pingfinder timer
  systemd:
    name: pingfinder.timer
    daemon_reload: true
    state: started
    enabled: true
