- name: Reload sysctl
  command: sysctl -p
  changed_when: true

- name: Update CA certificates
  command: update-ca-certificates
  changed_when: true

- name: Restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted
    enabled: true
