- name: Slurp private key
  slurp:
    src: /etc/wireguard/privatekey
  register: wg_private_b64

- name: Decode private key
  set_fact:
    wg_private: "{{ wg_private_b64['content'] | b64decode | trim }}"

- name: Slurp public key
  slurp:
    src: /etc/wireguard/publickey
  register: wg_public_b64

- name: Decode public key
  set_fact:
    wg_public: "{{ wg_public_b64['content'] | b64decode | trim }}"
