- name: Copy sysctl.conf
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload sysctl

- name: Copy sysctl.d/90-override.conf
  template:
    src: sysctl-override.conf.j2
    dest: /etc/sysctl.d/90-override.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload sysctl

- name: Set FQDN
  hostname:
    name: "{{ ansible_host }}"

- name: Update /etc/hosts with new hostname
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.0.1.*(?<!localhost)$"
    line: "127.0.0.1 {{ ansible_host }}"

- name: Create CA extras directory
  file:
    path: /usr/share/ca-certificates/extra
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy dn42 root CA
  copy:
    src: dn42-root-ca.crt
    dest: /usr/share/ca-certificates/extra/dn42.crt
    owner: root
    group: root
    mode: "0644"
  notify: Update CA certificates

- name: Enable dn42 root CA
  lineinfile:
    path: /etc/ca-certificates.conf
    line: "extra/dn42.crt"
    state: present

- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Copy /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"

- name: Create dummy0.netdev file
  template:
    src: dummy0.netdev.j2
    dest: /etc/systemd/network/dummy0.netdev
    mode: "0644"
  notify: Restart systemd-networkd

- name: Create dummy0.network file
  template:
    src: dummy0.network.j2
    dest: /etc/systemd/network/dummy0.network
    mode: "0644"
  notify: Restart systemd-networkd

- name: Run extra setup for anycast nodes
  include_tasks: anycast.yml
  when: inventory_hostname in groups["dn42_anycast"]

- name: Run extra setup for nat64 nodes
  include_tasks: nat64.yml
  when: inventory_hostname in groups["dn42_nat64"]

- name: Run extra setup for lite nodes
  include_tasks: lite.yml
  when: inventory_hostname in groups["dn42_lite"]
